NewsPaper/NewsPaper/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
  path('admin/', admin.site.urls),
  path('news/', include('news.urls')),
  path("accounts/", include("allauth.urls")),
  #path('accounts/', include('django.contrib.auth.urls')),
  #path("accounts/", include("accounts.urls")),
]

NewsPaper/news/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('',         views.PostList.as_view(), name='post_list'),
    path('<int:pk>', views.PostDetail.as_view(), name='post_detail'),
    path('search/',  views.PostSearch.as_view()),

    path('article/create/', views.CreatePost.as_view()),
    path('create/',         views.CreateNews.as_view()),

    path('<int:pk>/update/', views.UpdatePost.as_view()),

    path('<int:pk>/delete/', views.DeletePost.as_view()),

    path('subscriptions/', views.subscriptions, name='subscriptions')
]

NewsPaper/news/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Sum
from django.urls import reverse

class Author(models.Model):
  user=models.OneToOneField(User, on_delete = models.CASCADE)
  rating=models.IntegerField(default=0)

  class Meta:
    verbose_name = 'Автор'
    verbose_name_plural = 'Авторы'
  
  def update_rating(self):
    self.rating = Post.objects.filter(author_id=self.id).aggregate(Sum('rating'))['rating__sum']*3 + \
      Comment.objects.filter(user_id=self.user.id).aggregate(Sum('rating'))['rating__sum'] + \
      Comment.objects.filter(post_id__in = [q['id'] for q in Post.objects.filter(author_id=self.id).values('id')]).aggregate(Sum('rating'))['rating__sum']
    self.save()

  def __str__(self):
    return self.user.username

class Category(models.Model):
  name=models.TextField(unique=True)

  class Meta:
    verbose_name = 'Категория'
    verbose_name_plural = 'Категории'

  def __str__(self):
    return self.name

class Post(models.Model):
  author=models.ForeignKey(Author, on_delete = models.CASCADE)
  isnews=models.BooleanField(default = False)
  created=models.DateTimeField(auto_now_add=True)
  categories=models.ManyToManyField(Category, through = 'PostCategory')
  title=models.CharField(max_length = 64)
  text=models.CharField(max_length = 4096)
  rating=models.IntegerField(default=0)
  
  class Meta:
    verbose_name = 'Новость'
    verbose_name_plural = 'Новости'

  def preview(self):
    return (self.text[:20] + '...') if len(self.text) > 20 else self.text
  
  def like(self):
    self.rating += 1
    self.save()

  def dislike(self):
    self.rating -= 1
    self.save()

  def __str__(self):
    return self.title

  def get_absolute_url(self):
        return reverse('post_detail', args=[str(self.id)])
  
class PostCategory(models.Model):
  post=models.ForeignKey(Post, on_delete = models.CASCADE)
  category=models.ForeignKey(Category, on_delete = models.CASCADE)

  class Meta:
    verbose_name = 'Категория новости'
    verbose_name_plural = 'Категории новостей'

  def __str__(self):
    return f'{self.post} ({self.category})'

class Comment(models.Model):
  post=models.ForeignKey(Post, on_delete = models.CASCADE)
  user=models.ForeignKey(User, on_delete = models.CASCADE)
  text=models.CharField(max_length = 4096)
  created=models.DateTimeField(auto_now_add=True)
  rating=models.IntegerField(default=0)

  class Meta:
    verbose_name = 'Комментарий'
    verbose_name_plural = 'Комментарии'

  def like(self):
    self.rating += 1
    self.save()

  def dislike(self):
    self.rating -= 1
    self.save()

  def __str__(self):
    return f'{self.user.username} про "{self.post}"'

class Subscription(models.Model):
  user = models.ForeignKey(
    to=User,
    on_delete=models.CASCADE,
    related_name='subscriptions'
  )
  category = models.ForeignKey(
    to='Category',
    on_delete=models.CASCADE,
    related_name='subscriptions',
  )

  class Meta:
    verbose_name = 'Подписка'
    verbose_name_plural = 'Подписки'
    constraints = [
      models.UniqueConstraint(fields=['user', 'category'], name='unique subscriptions')
    ]

  def __str__(self):
    return f'{self.user.username} подписан на "{self.category}"'

NewsPaper/templates/default.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>{%block title%}{%endblock title%}</title>
        <!-- Favicon-->
        <!--link rel="icon" type="image/x-icon" href="assets/favicon.ico" /-->
        <!-- Core theme CSS (includes Bootstrap)-->
		{% load static %}
		{% load custom_filters %}
		{% load custom_tags %}
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        <!-- Responsive navbar-->
		<nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top">
			<div class="container">
				<button class="navbar-toggler" type="button" data-toggle="collapse"
					   data-target="#navbarResponsive"
					   aria-controls="navbarResponsive" aria-expanded="false"
					   aria-label="Toggle navigation">
				   <span class="navbar-toggler-icon"></span>
				</button>
				<div class="collapse navbar-collapse" id="navbarResponsive">
				   <ul class="navbar-nav ml-auto">
					<li class="nav-item active">
						<a class="nav-link" href="/news">Новости на {% now %}</a>
					</li>
					<li class="nav-item active">
						<a class="nav-link" href="/news/search">Поиск</a>
					</li>
					{% if perms.news.add_post %}
					<li class="nav-item active">
						<a class="nav-link" href="/news/article/create">Написать статью</a>
					</li>
					<li class="nav-item active">
						<a class="nav-link" href="/news/create">Написать новость</a>
					</li>
					{% endif %}
			  </ul>
				</div>
			</div>
		</nav>
		<div class="container">
		   <div class="row">
			   <div class="col-lg-12 text-center">
				   {% block content %}
				   {% endblock content %}
			   </div>
		   </div>
		</div>
	</body>
</html>